# Generated by Django 4.2.1 on 2023-08-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='count',
            new_name='likes',
        ),
    ]
