# Generated by Django 5.0.6 on 2024-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_likes_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
